import Head from "next/head";
import Image from "next/image";
import { signOut } from "next-auth/react";
import { deleteCookie, getCookie } from "cookies-next";
import LandingPage from "../components/LandingPage/LandingPage";
import { useSession } from "next-auth/react";

export default function Home() {
  const { data: session } = useSession();
  // const handleLogout = () => {
  //   signOut();
  //   deleteCookie("next-auth.session-token");
  //   deleteCookie("userToken");
  // };
  return (
    <div>
      <Head>
        <title>Booking App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <h1>ITS HOME</h1>
      <button onClick={handleLogout}>logout</button> */}
      <LandingPage />
      {/* <FilterComponent /> */}
      {/* <SingleResultPage /> */}
    </div>
  );
}

// export async function getServerSideProps(context) {
//   const session = await getSession(context);
//   console.log(session, "session");
//   // const isCookie = await getCookie('cookieToken');
//   // const isCookie = context.req.headers['cookieToken']  ;
//   const { cookieToken } = cookies(context)
//   if (!session && !cookieToken) {
//     return {
//       redirect: {
//         destination: "/login",
//         permanent: false,
//       },
//     };
//   }
//   return { props: {} };
// }
